In [2]:
## Singular Values Decomposition

import numpy as np

A = np.array([[1, 2, 3], [2, 3, 4], [4, 5, 6], [6, 7, 8]])
A

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
U, s, Vt = np.linalg.svd(A)
print(U)
print(s)
print(Vt)

[[-0.22274652  0.73729528  0.57511721  0.27571699]
 [-0.32727663  0.49882082 -0.79952884  0.06943652]
 [-0.53633685  0.02187191  0.16126466 -0.82816551]
 [-0.74539707 -0.455077    0.06314697  0.483012  ]]
[1.63608531e+01 1.14999430e+00 3.36020246e-16]
[[-0.4581075  -0.57006726 -0.68202701]
 [-0.7896017  -0.09141475  0.60677219]
 [ 0.40824829 -0.81649658  0.40824829]]


In [4]:
S = np.zeros(np.shape(A))
S


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.fill_diagonal(S, s)
S


array([[1.63608531e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.14999430e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.36020246e-16],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

### La suma de los valores singulares, es la cantidad total de la varianza de una matriz.

Los valores singulares, asi nada mas vienen en la escala de la matriz, asi que no podemos comporarlos con los valores singulares de otras matrices (otros datasets).

Por lo que es mejor convertir los valores singuales al total de la varianza aplicando la normalizacion.

Cada valor singular se divide por la suma de todos los valores singulares, y se multiplica por 100. 
$$

\sigma_i = \frac{\sigma_i}{\sum_{j=1}^n \sigma_j} \times 100

$$

### SVD
Va a descompiner una matriz en 3 matrices llamadas los vectors singulares izquierdos, los valores singulares y los vectors singulares derechos.

SVD se puede obtener de la eigendescomposicion de A por A transpuesta.

Los primeros r vectores singulares izquierdos, te dan una base ortonormal para el espacio de columnas matricial, mientras que los vectores singulares posteriores te dan una base ortonormal para espacio nulo izquierdo.

Lo mismo para los vectores singulares derechos, que te dan una base ortonormal para el espacio de filas matricial, mientras que los vectores singulares posteriores te dan una base ortonormal para espacio nulo derecho.

El numero de valores singulares no cero, te va a dar el rango de la matriz.




