### Matrices
Una matriz es una estructura matemática que organiza números, símbolos o expresiones en filas y columnas rectangulares. Es básicamente una tabla ordenada de elementos.
Características principales:
Una matriz se representa entre paréntesis o corchetes, y cada elemento tiene una posición específica determinada por su fila y columna. Por ejemplo:



A = [2  1  3]

    [4  0  5]

    [1  2  7]

Esta es una matriz de 3×3 (3 filas por 3 columnas).
Elementos clave:

Dimensión: Se expresa como m×n, donde m es el número de filas y n el número de columnas
Elementos: Cada número en la matriz se llama elemento y se denota como aᵢⱼ (elemento en la fila i, columna j)
Tipos especiales: Existen matrices cuadradas (mismo número de filas y columnas), matrices identidad, matrices nulas, etc.

Usos principales:
Las matrices son fundamentales en álgebra lineal y tienen aplicaciones prácticas en:

Resolución de sistemas de ecuaciones lineales
Transformaciones geométricas
Programación y ciencias de la computación
Estadística y análisis de datos
Física e ingeniería
Gráficos por computadora

Las matrices permiten realizar operaciones como suma, multiplicación y encontrar determinantes, lo que las
convierte en herramientas poderosas para resolver problemas matemáticos complejos de manera organizada.

### Tipos de matrices
![Tipos de matrices](image.png)

Una matriz es una tabla bidimensional de números, símbolos o expresiones organizados en filas y columnas. Pero en un contexto geometrico es una transformacion lineanl. Porlo que una matriz solo es una tranformacion linea.

Una transformacion es la forma elegante de llamar a una funcion.

Transformacion => Funcion f(x)

![Transformacion lineal](image2.png)

En algebra lineal una transformacion es una funcion toma un vector de entrada y devuelve otro vector de salida.
![Transformacion lineal](image3.png)

Se le llama transformacion, porque es mas facil ver como el vector de entrada X, transforma su posicion en el vector de salida Y, por medio de multiplicarse por la matriz A.
![Transformacion lineal](image4.png)

Pero realmente lo que se hace es tomar todos los vectores de ese espacio es decir el espacio vectorial y transformar el espacio en un nuevo espacio vectorial. Por ejemplo aplastar y transformar el espacio.
![Transformacion del espacio por una transformacion](image5.png)

El algebra lineal solo se limita a transformaciones lineales.
![Transformacion lineal](image6.png)

Para que una transformacion se considere lineal:
1.  Lineal significa que todas las lineas se conservan como lineas paralelas y equidistantes unas de otras.
2.  El punto (0,0) se transforma en (0,0) y cualquier otro punto se transforma de manera proporcional. Es decir el origen se mantiene fijo.
![Transformacion lineal punto fijo](image7.png)
![Transformacion lineal equidistante](image8.png)

#### Como se pueden describir estas transformaciones de forma numerica?

Tengo un vector de entrada [x1, x2, x3] => ????? => [y1, y2, y3]

Ejemplo considerar el vector v = (-1) i + (2) j
![Transformacion lineal vector v](image9.png)

Si aplicamos una transformacion y seguimos donde van a caer estos vectores 
![Transformacion lineal](image10.png)
![Transformacion lineal](image11.png)
![Transformacion lineal](image12.png)
![Transformacion lineal](image13.png)
![Transformacion lineal](image14.png)

La transformacion lineal de dos dimensiones esta descrita completamente por cuatro numeros,  las coordenadas donde aterriza i y las coordenadas donde aterriza j.
![Transformacion lineal](image15.png)
![Transformacion lineal](image16.png)
Esto corresponde a sumar versiones escaladas de nuestros nuevos vectores base
![Transformacion lineal](image17.png)

Podemos generalizar esto con ayuda del algebra lineal, matriz 2x2, empaca la informacion de la transformacion lineal en una matriz, la primer columna donde aterriza el primer vector base, la segunda columna donde aterriza el segundo vector base. Esto se conoce como el producto de vector por matriz.
![Transformacion lineal](image18.png)

Rotacion del espacio 90 grados
![Transformacion lineal](image19.png)

Si la transformacion lineal aplasta el espacio en una linea, quiere decir que los vectores de la transformacion erean linealmente dependiente.
![Transformacion lineal](image20.png)

En las matrices las columnas represntan las coordenadas, donde los vectores base van a caer, el producto vector por matriz en si representa la forma en que se computa lo que esa transformacion le ha echo al vector dado.

Temas base del Algebra linea:

1.  Vectores
2.  Combinaciones lineales
3.  Matrices como transformaciones lineales
4.  Multiplicacion de matriz
5.  Determinante 
6.  Matriz inverza
7. Producto punto y producto cruz
8.  Cambio de base
9.  Autovectores o vectores propios
10. Espacios vectoriales


### Las matrices

Se van a denotar con letras mayusculas y en negritas.

matriz **A** o matriz **M**

Las matrices se miden por la cantidad de filas y columas que tienen.

![Matriz](image21.png)

Esta matriz se llama A es de 3x5 es decir 3 filas y 5 columnas.
![Matriz](image22.png)

Que pasa sinos queremos referir a un elemento en especifico, primero te vas a referir a la fila y luego a la columna. El elemento 8 se encuentra en la fila 3 columna 4.
![Matriz](image23.png)

Esta notacion aplica solo en matematicas.



In [1]:
import numpy as np

In [2]:
Matriz = np.array([[1,3,5,7,9], [0,2,4,6,8], [1,4,7,8,9]])
Matriz

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8],
       [1, 4, 7, 8, 9]])

Para seleccionar el 8 como lo habiamos visto en matematicas seria el elemento de la fila 3 columna 4.
![Matriz](image24.png)

In [3]:
# En python el indice inicial es 0, por lo que la primer fila es 0 y la primer columna es 0.
# Pero en python no se cuenta con la notacion de fila y columna, sino que se cuenta con la notacion de indice.
# Por lo que para seleccionar el 8 como lo habiamos visto en matematicas seria el elemento de la fila 3 columna 4.
# En python seria la fila 2 columna 3.
Matriz[2,3]


np.int64(8)

In [4]:
# -4, -3, -2, -1, 0, 1, 2, 3, 4
A = np.arange(-4,5)
print(A)

[-4 -3 -2 -1  0  1  2  3  4]


In [5]:
A = np.arange(60)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [7]:
A = np.arange(60).reshape(6,10) # creamos una matriz de 6 filas 10 columnas
print(A)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [8]:
A[2,3] # elemento de la 3 fila cuarta columna

np.int64(23)

In [9]:
# seleccionar una sub matriz, el ultimo numero no es incluido, es decir seleccionamos la fila 
# 1 a la fila 3 porque la 4  no esta incluida, de uno en uno, y de la columna 0 a la 5 pero
# la columna 5 no incluida
A[1:4:1, 0:5]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### Tipos de matrices 

Matrices aleatorias
Matrices que hacemos con numeros random

In [11]:
## Creamos una matriz aleatoria de 5 x 7

A = np.random.rand(3,2)
A

array([[0.27384223, 0.33446803],
       [0.84292016, 0.25656738],
       [0.72788278, 0.03402687]])

## Matrices cuadradas vs rectangulares

Las matrices cuadradas son aquellas que el numero de filas es igual al numero de columnas, es decir, una matriz de 3x3, 4x4, 5x5, etc.
Las matrices rectangulares son aquellas que el numero de filas es diferente al numero de columnas, es decir, una matriz de 3x2, 4x3, 5x4, etc.
![matrices_cuadradas_vs_rectangulares](image25.png)

Dentro de las matrices rectangulares tenemos:

Matrices altas, es decir, matrices con mas filas que columnas, es decir, una matriz de 3x2, 4x3, 5x4, etc.
![matrices_altas](image26.png)

Matrices anchas, es decir, matrices con mas columnas que filas, es decir, una matriz de 2x3, 3x4, 4x5, etc.
![matrices_anchas](image27.png)

Las matrices que mas vamos a encontrar en la naturaleza son las matrices rectangulares altas. La matriz mas util es una matriz cuadrada.

##### Matrices diagonales
La diagonal de una matriz es:
![matriz_diagonal](image28.png)

La matrices rectangulares si pueden tener diagonales




In [12]:
A = np.arange(60).reshape(6,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

Para python la diagonal de esta matriz seria 
![matriz_diagonal](image29.png)

In [13]:
A = np.diag(A)
A


array([ 0, 11, 22, 33, 44, 55])

La matriz diagonal formalmete solo se puede dar en matrices cuadradas

Una matriz diagonal es una matriz cuadrada donde solo tiene numeros en su diagonal principal, todos los demas son ceros.
![matriz_diagonal](image30.png)



### Matrices triangulares
Son matrices cuadradas en las cuales todos los elementos por encima de la diagonal principal son cero (matriz triangular alta), o todos los elementos por debajo de la diagonal principal son cero (matriz triangular baja).

![matriz_triangular](image31.png)




In [14]:
B = np.arange(64).reshape(8,8)
B


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [15]:
Balto = np.triu(B)
Balto

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  0, 18, 19, 20, 21, 22, 23],
       [ 0,  0,  0, 27, 28, 29, 30, 31],
       [ 0,  0,  0,  0, 36, 37, 38, 39],
       [ 0,  0,  0,  0,  0, 45, 46, 47],
       [ 0,  0,  0,  0,  0,  0, 54, 55],
       [ 0,  0,  0,  0,  0,  0,  0, 63]])

In [16]:
Bbajo = np.tril(B)
Bbajo

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  9,  0,  0,  0,  0,  0,  0],
       [16, 17, 18,  0,  0,  0,  0,  0],
       [24, 25, 26, 27,  0,  0,  0,  0],
       [32, 33, 34, 35, 36,  0,  0,  0],
       [40, 41, 42, 43, 44, 45,  0,  0],
       [48, 49, 50, 51, 52, 53, 54,  0],
       [56, 57, 58, 59, 60, 61, 62, 63]])

### Matriz identidad 
Es una matriz cuadrada donde la diagonal son puros unos y los demas elementos son cero.
![matriz_identidad](image32.png)
Es importante porque nos permite multiplicar por uno cuando se trata de matrices 
![matriz_identidad](image33.png)
Las matrices no pueden multiplicar por escalares y por eso se multiplica por la matriz identidad.

La matriz identidad siempre se llama I, y estan dadas por un sub indice que indica su tamanio, si fuers sub indice 4 es la matriz identidad 4x4 cuatro filas 4 columnas.
![matriz_identidad](image34.png)

Una parte importante de resolver sistemas de ecuaciones, es con matrices identidades.


In [17]:
## matriz identidad en python
I = np.eye(4)
I


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matriz de ceros
Una matriz de ceros es una matriz que tiene todos sus elementos igual a cero.

In [18]:
ceros = np.zeros((4,4))
ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Operaciones con matrices

#### Operaciones faciles
Son las que hacen sus operaciones elemento por elemento y son muy **Intituivas** de entender: sumar resta y multiplicacion por escalares.
![operaciones_faciles](image35.png)

#### Operaciones dificiles
Requieren entendimiento especial sobre las matrices y no son tan sencillas de aplicar. Multiplicacion de matrices, transoponer y matrices simetricas.
![operaciones_dificiles](image36.png)



In [ ]:
## Sumar matrices
M1 = np.array([[2, 3, 4], [1, 2, 4]])
M2 = np.array([[0, 3, 1], [-1, -4, 2]])
M1 + M2
# La suma de matrices solo puede ser realizada si tienen la misma dimension(tamanio)

array([[ 2,  6,  5],
       [ 0, -2,  6]])

![sumar_matrices](image37.png)

In [20]:
np.add(M1, M2)


array([[ 2,  6,  5],
       [ 0, -2,  6]])

In [21]:
## La suma con un escalar matematicamente no es posible, pero en python crea una matriz cuadrada
## del mismo tamanio que la matriz a sumar  con el escalar en cada elemntosy suma el escalar a cada elemento de la matriz a.

A = np.arange(9).reshape(3, 3)
A + 6


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Multiplicar por escalar
![multiplicar_escalar](image38.png)

In [22]:
### La multiplicacion por escalar es posible 
A = np.arange(9).reshape(3, 3)
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### Multiplicacion Hadamard
Es multiplicar cada uno por su termino
![multiplicar_hadamard](image39.png)

In [23]:
### Multiplicacion Hadamard
A = np.arange(9).reshape(3, 3)
B = np.arange(9).reshape(3, 3)
print(A)
print(B)
A * B


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

### Multiplicacion de matrices

Lo mas importante es que el numero de columnas de la primer matriz A es igual al numero de filas de la segunda matriz B. Es decir que las columnas cuadre.
![multiplicar_matrices](image40.png)

Como matriz de resultado de esta multiplicacion sera una nueva matriz, la cual tendra de tamanio el numero de filas de A por el numero de columnas de B.
![multiplicar_matrices_resultado](image41.png)

El orden de los factores si altera el producto en multiplicacion de matrices, por lo que no es conmutativa la operacion de multiplicacion.
![multiplicar_matrices_orden](image42.png)


In [24]:
## Multipliacacion en python
A = np.arange(48).reshape(6, 8)
B = np.arange(24).reshape(8, 3)
print(A)
print(B)
A @ B


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[ 420,  448,  476],
       [1092, 1184, 1276],
       [1764, 1920, 2076],
       [2436, 2656, 2876],
       [3108, 3392, 3676],
       [3780, 4128, 4476]])

Las combinaciones lineales se pueden representar con el producto de una matriz por vector.
![combinacion_lineal](image43.png)


### Interpretacion geometrica de la multiplicacion de matrices

Como una matriz se puede interpretar como una transformacion lineal?

Una matriz es una transformacion lineal, es decir es una funcion que transforma un vector en otro vector.

Un vector con coordenadas X, Y seria  (X) i + (Y) j
![vector](image44.png)


Si se lleva un registro donde aterriza i y j se puede saber donde va a caer otro vector.
![vector_transformado](image45.png)

En la vida real vas a querer describir los efectos de aplicar una transformacion y luego otra.

Ejemplo rotar el plano 90 grado y luego aplicamos un corte (shear). 
![transformacion_geometrica](image46.png)

Esta transformacion lineal compuesta de rotacion y corte se llama "Composicion", puede ser descrita por una matriz de  de donde i y j aterrizan.
![transformacion_composicion](image47.png)

La nueva matriz realiza las dos operaciones al instante como si se realizara primero la rotacion y luego el corte.
Esto seria el procedimiento original 
![transformacion_una_tras_otra](image48.png)

La matriz de composicion es en si el producto de las dos matrices originales que realizan la transformaciones una tras otra
![transformacion_composicion_producto](image49.png)

En algebra lineal leemos de derecha a izquierda es decir, producto de la matriz de la derecha por matriz de  la izquierda.
![transformacion_composicion_producto_2](image50.png)

![columna 1](image51.png)
![Columna 2](image52.png)

La multiplicacion de matrices corresponde a aplicar una transformacion lineal, una detras de otra. 
El orden de la aplicacion de las transformaciones es de derecha a izquierda. Por lo que el orden  no es lo mismo por ejemolo primero rotar 90 grador y luego cortar, que cortar y luego rotar, por lo que el orden de la multiplicacion de matrices si importa y mucho.

La multiplicacion de matrices es asociativa, (AB)C = A(BC).
Las multiplicacion de matrices no es conmutativa, A*B != B*A.

La multiplicacion de matrices nos puede servir para la descomposicion:
![descomposicion](image53.png)

Vamos a ver:
-   Descomposicion Ortogonal QR
-   Descomposicion LU
-   Eigendescomposicio 
-   Descomposicion SVD (descomposion en valores singulares)


Al multiplicar dos matrices, estoy componiendo una matriz nueva, es decir genero una nueva transformacion, compuesta de las transformaciones de las matrices originales.

La descomposicion es entonces Una descomposición es el proceso de dividir o separar algo complejo en partes más simples y manejables.  En matrices, la descomposición (o factorización matricial) consiste en expresar una matriz como el producto de dos o más matrices con propiedades específicas

Si yo combino 2,3,4 Transformaciones lineales voy a obtner una nueva transformacion y es el resultado de haber aplicado todas esas transformaciones lineales juntas.



### Transponer una matriz
Las filas de una matriz se convertirán en columnas y viceversa las columnas se combierten en filas.
![transponer_matriz](image54.png)


In [25]:
A = np.arange(12).reshape(6, 2)
print(A)
A.T


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

Entre matrices no existe el producto punto, la operacion importante es el producto de matrices.

(LIVE).T = E.T V.T I.T L.T

Donde el transpuesto del producto de varias matrices multiplicadas  = Matrices individuales transpuestas y  multiplicadas.

### Matriz simetrica 
Puedes entenderla de dos maneras diferentes: 
1) La matriz simetrica es igual a su transpuesta.
2) La matriz simetrica tiene los mismos valores en la diagonal principal y en la diagonal secundaria.
![matriz_simetrica](image55.png)

Para forzar a una matriz simetrica es multiplicarla por su transpuesta y se obtiene una simetrica.



In [26]:
### ejemplo 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A.T
C = A @ B
C

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [27]:
C.T

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

### Resumen de matrices
1.  Las matrices son transformaciones lineales
2.  Hay varias categorias de matrices especiales, hay que conocer sus propiedades:
    - Matriz identidad: Es una matriz cuadrada con unos en la diagonal principal y ceros en el resto de la matriz.
    - Matriz simetrica: Es una matriz cuadrada que es igual a su transpuesta.
    - Matriz diagonal: Es una matriz cuadrada con ceros en la diagonal principal y unos en el resto de la matriz.
    - Matriz singular: Es una matriz cuadrada que no tiene inversa.
    - Matriz invertible: Es una matriz cuadrada que tiene inversa.
3.  Hay operaciones como la suma, resta, multiplicacion por un escalar y Hadamard son sencillas.
4.  Hay operaciones como la multiplicacion de matrices que no es muy intituiva pero no es dificil.
5.  Las matrices simetricas se espejean a traves de la diagonal cada fila es igual a su columna correspondiente.



## Matrices rectangulares
La matrices rectangulares pueden transformar vectores de una dimencion a vectores en otra dimension. 
![matriz_rectangulares](image56.png)
Es totalmente viable, el hablar de transformaciones entre dimensiones, como soln las transformaciones que toman vectores 2D y los combierten en vectores 3D.
![matriz_rectangulares_2](image57.png)
Para que una transformacion sea lineal solo hay que asegurarse que la cuadricula permanece paralela y equidistante, asi como que el origen se queda en el mismo lugar.
![transformacion_lineal](image58.png)
En la matriz de transformacion tenemos las columnas donde cae el vector i y la columna donde cael vector j.
![transformacion_lineal_2](image59.png)

Es decir una matriz de 3(filas) x 2 (columnas), una matriz rectangulares puede transformar vectores de 2D a vectores de 3D.
El span de columnas de esta matriz es un plano de 2d, que corta el espacio de 3d, por el origen.

Entonces si nos encontramos una matriz rectangular, es una transformacion que puede tramsformar el espacio de 2d en 3 dimenciones.

En caso contrario si tenemos una matriz de 2(filas) x 3 (columnas), una matriz rectangulares puede transformar vectores de 3D a vectores de 2D. Las tres columnas indican que comenzamos en un espacio base que tiene tres dimensiones y las 2 filas indican que el espacio de aterrizaje es un espacio de 2 dimenciones.
![transformacion_lineal_3](image60.png)

Se puede tener tambien transformaciones de 2D a una dimension 1D. Seria una tranfomacion que toma vectores 2D y escupe numeros en la recta numerica.
![transformacion_lineal_4](image61.png)
Este tipo de transfomacion seria mapeda con una matriz de [1 2], cada una de sus dos columnas tiene una salida.
![transformacion_lineal_5](image62.png)









