### Que son las matrices inversas y porque son inportantes?


El principal problema a resolver son sistemas de ecuaciones lineales.
![Sistema de ecuaciones lineales](image.png)

En algebra lineal no es posible simplemente tomar la matriz y pasarla dividiendola.
![Matriz inversa](image2.png)

La alternativa son las matrices inversas. Buscamos una transformacion escalada por una matriz "A" que nos permita convertir el vector "x" en el vector "v".
![Matriz inversa](image3.png)

Tenemos los el siguiente sistema de ecuaciones que se veria de la siguiente forma.
![Sistema de ecuaciones lineales](image4.png)

Para saber si el sitema tiene solucion, debemos calcular el determinate de "A" si es cero, estamos aplastando a una dimension mas baja, lo mas probable es que no tenga solucion.

Si el det(A) es diferente de 0, el sistema tiene solucion. Por lo que, solo un vector va acaer sobre el vector "v", y se encuentra con la transformacion inversa.
![Sistema de ecuaciones lineales](image5.png)

Ejemplo si la transformacion A es un giro 90 grados con sentido contrario a las agujas del reloj.
![Matriz inversa](image6.png)

La transformacion inversa es un giro de 90 grados en sentido de las agujas del reloj.
![Matriz inversa](image7.png)


El mismo caso si A es un corte a la derecha, A inversa es un corte a la izquierda.

Es decir tenemos que si aplicamos la inversa de A, y luego la matriz A, el resultado es que quedamos como iniciamos.
![Matriz inversa](image8.png)

Una vez tenemos la inverza podemos multiplicar por la matriz A, y obtendremos la identidad.
![Matriz inversa](image9.png)

La matriz identidad no cambia en nada.
![Matriz inversa](image10.png)

Para un sistema de ecuaciones de 2x2, debemos tener generalmete una solucion unica para estas dos variables, 
por lo general donde el det(A) es diferente de 0, tenemos una solucion unica, que los vectores no sean linealmente dependientes.
![Matriz inversa](image11.png)

Cuando el determinante es 0 det(A) = 0, la matriz aplasta el espacio a una dimension mas pequenia. Porlo que no hay inverza.

Cuando el determinate es 0, existe solucion, el vector "v" debe estar en la linea resultante, pero es muy poco probable que suceda.

### Obtener la matriz Inversa
Si tengo un sistema de ecuaciones podemos encontrar valores de variables si conocemos la matriz inversa y se multiplica por "V".
![Matriz inversa](image12.png)

Calcular la matriz inversa depende de calcular el determinante de la matriz. Mientras mas grande la matriz, mas dificil es computar el determinate.

Para calcular una matriz de 2x2
![Matriz inversa](image13.png)

Tipos de 
![Matriz inversa](image14.png)

Matriz pseudo-inverza
![Matriz pseudo-inversa](image15.png)


Matriz inversa: Garantiza que al multiplicar la matriz inversas por la original, va a darte la matriz identidad.
Matriz pseudo-inversa: Garantiza que al multiplicar la matriz pseudo-inversa por la original, tal vez resulta en algo similar a la matriz de identidad.

### Calcular matriz inverza
![Matriz inversa](image16.png)
![Matriz inversa](image17.png)
![Matriz inversa](image18.png)














In [1]:
## Calcular inversa python
import numpy as np

A = np.array([[1,4],[4,9]])
A

array([[1, 4],
       [4, 9]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [3]:
## Obtenemos la matriz identidad
A@Ainv

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

![matriz_inversa](image19.png)

La pseudo-inversa de Moore Penrose es una generalización de la inversa de una matriz cuadrada a matrices no cuadradas.
La mayoria de matrices no son cuadradas ni de rango completo.
![pseudo_inversa](image20.png)

In [4]:
A = np.array([[1,4],[3,12]])
A

array([[ 1,  4],
       [ 3, 12]])

In [5]:
Apinv = np.linalg.pinv(A)
Apinv

array([[0.00588235, 0.01764706],
       [0.02352941, 0.07058824]])

In [6]:
A@Apinv

array([[0.1, 0.3],
       [0.3, 0.9]])

Para calcular la matriz inverza, se requieren muchas operaciones, los numeros decimales generan problemas en los calculos porque el usar decimales representa un metodo estocastico para resolver los problemas de precision. Si hay muchos decimales debemos truncar para almacenarlo todo. El calculo de las matrices psudo-inversarsas suelen ser numericamete inestables. Por eso se intenta calcular la inversa por el exceso de operaciones.

1.  La inversa es una matriz que si multiplicamos por la matriz original, nos da la matriz identidad.
2.  Cada matriz solo tiene una inversa de verdad.
3.  Si no escuadrada y de rango completo, debemos usar la psudo-inversa de Moore Penrose.
4.  Solo una inversa por matriz.
5.  Calcular inversas es dificil hasta para la computadora.
