In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
# obtener los eigenvectores de A, eigenvalores
eigenvalores, eigenvectores = np.linalg.eig(A)
eigenvalores, eigenvectores

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Se nesesitan que los eigenvectores y eigenvalores sean de rango completo? Que sus columnas no sean linealmetes dependietes, que su deteminate es 0, si se puede


In [4]:
A = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
np.linalg.det(A)

np.float64(0.0)

In [7]:
# El determinate de esta matriz singular, quiere decir que almenos un eigenvalor sera cero
eigenvalores, eigenvectores = np.linalg.eig(A)
eigenvalores, eigenvectores

(array([ 1.61168440e+01, -1.11684397e+00, -2.95854556e-16]),
 array([[-0.46454727, -0.88290596,  0.40824829],
        [-0.57079553, -0.23952042, -0.81649658],
        [-0.67704379,  0.40386512,  0.40824829]]))